name: build-shotcut-linux

on: [push]

env:
  IMAGE_NAME: mltframework/shotcut-build:qt5.15.1-ubuntu18.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd scripts
          VERSION=$(date +"%y%m%d")
          docker run -v $PWD:/root/shotcut $IMAGE_NAME
          mv shotcut.txz shotcut-linux-x86_64-$VERSION.txz
          mv src.txz shotcut-src-$VERSION.txz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-portable-archive
          path: |
            scripts/shotcut-linux-x86_64-*.txz

      - name: Upload to S3
        uses: mltframework/s3cmd-action@v0
        with:
          args: >-
            --access_key=${{ secrets.AWS_ACCESS_KEY }}
            --secret_key=${{ secrets.AWS_SECRET_KEY }}
            --acl-public
            --stop-on-error
            put scripts/*.txz s3://builds.us.meltytech/shotcut/
