name: build-shotcut-linux

on: [push]

env:
  IMAGE_NAME: mltframework/shotcut-build:qt5.15.1-ubuntu18.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd scripts
          docker run -v $PWD:/root/shotcut $IMAGE_NAME
