name: build-shotcut-linux

on:
  workflow_dispatch:
  schedule:
    # nightly
    - cron: '0 8 * * *'

env:
  IMAGE_NAME: mltframework/shotcut-build:qt5.15.1-ubuntu18.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd scripts
          VERSION=$(date +"%y%m%d")
          echo CLEANUP=0 > build-shotcut.conf
          echo SHOTCUT_VERSION=\"$VERSION\" >> build-shotcut.conf
          docker run -v $PWD:/root/shotcut $IMAGE_NAME
          mv shotcut.txz shotcut-linux-x86_64-$VERSION.txz
          mv src.txz shotcut-src-$VERSION.txz
          echo put version into AppImage
          mkdir ../packaging/linux/Shotcut
          echo $VERSION > ../packaging/linux/Shotcut/VERSION

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-portable
          path: |
            scripts/shotcut-linux-x86_64-*.txz

      - name: Upload portable and source archives to S3
        uses: mltframework/s3cmd-action@v0
        with:
          args: >-
            --access_key=${{ secrets.AWS_ACCESS_KEY }}
            --secret_key=${{ secrets.AWS_SECRET_KEY }}
            --acl-public
            --stop-on-error
            put scripts/*.txz s3://builds.us.meltytech/shotcut/

      - name: Package AppImage
        run: |
          sudo apt install desktop-file-utils
          cd packaging/linux
          wget https://raw.githubusercontent.com/probonopd/AppImages/master/pkg2appimage
          bash -ex pkg2appimage appimage/appimage.yml

      - name: Upload AppImage to S3
        uses: mltframework/s3cmd-action@v0
        with:
          args: >-
            --access_key=${{ secrets.AWS_ACCESS_KEY }}
            --secret_key=${{ secrets.AWS_SECRET_KEY }}
            --acl-public
            --stop-on-error
            put packaging/linux/out/*.AppImage s3://builds.us.meltytech/shotcut/
