name: build-shotcut-windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel gcc git cmake nasm yasm zip tar xz gzip bzip2
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-libvorbis
            mingw-w64-x86_64-libtheora
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-fftw
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-libsamplerate
            mingw-w64-x86_64-libexif
            mingw-w64-x86_64-eigen3
            mingw-w64-x86_64-nsis
            mingw-w64-x86_64-sox
            mingw-w64-x86_64-dlfcn
            mingw-w64-x86_64-rubberband
            mingw-w64-x86_64-vid.stab
            mingw-w64-x86_64-libepoxy
            mingw-w64-x86_64-lame
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-osslsigncode
            mingw-w64-x86_64-libmfx
            mingw-w64-x86_64-libvpx
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-opus
            mingw-w64-x86_64-x264
            mingw-w64-x86_64-x265

      - uses: actions/checkout@v2

      - name: Build
        shell: msys2 {0}
        run: |
          VERSION=$(date +"%y%m%d")
          echo VERSION=$VERSION
          pushd "$HOME"
          echo Downloading prebuilt SWH LADSPA plugins
          curl -LO --no-progress-meter https://s3.amazonaws.com/misc.meltymedia/shotcut-build/swh-plugins-win64-0.4.15.tar.xz
          echo Downloading a few other prebuilt dependencies
          curl -LO --no-progress-meter https://s3.amazonaws.com/misc.meltymedia/shotcut-build/mlt-prebuilt-mingw64-v3.txz
          echo Extracting prebuilt dependencies
          tar -xJf mlt-prebuilt-mingw64-v3.txz
          mkdir Qt
          cd Qt
          echo Downloading Qt
          curl -LO --no-progress-meter https://s3.amazonaws.com/misc.meltymedia/shotcut-build/qt-5.15.1-x64-mingw810.txz
          echo Extracting Qt
          tar -xJf qt-5.15.1-x64-mingw810.txz
          popd
          echo Running the build script
          echo INSTALL_DIR=\"$PWD/build\" > build-shotcut.conf
          echo SHOTCUT_VERSION=\"$VERSION\" >> build-shotcut.conf
          bash scripts/build-shotcut-msys2.sh
          pushd build
          echo Packaging the portable zip
          zip -gr shotcut-win64-$VERSION.zip Shotcut
          echo Packaging the installer
          makensis shotcut.nsi
          mv shotcut-setup.exe shotcut-win64-$VERSION.exe
          popd
          echo Done

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-portable
          path: ./build/Shotcut/

      - name: Upload packages to S3
        uses: mltframework/s3cmd-action@v0
        with:
          args: >-
            --access_key=${{ secrets.AWS_ACCESS_KEY }}
            --secret_key=${{ secrets.AWS_SECRET_KEY }}
            --acl-public
            --stop-on-error
            put ./build/*.{exe,zip} s3://builds.us.meltytech/shotcut/
