name: build-shotcut-linux

on: [push]

env:
  IMAGE_NAME: mltframework/shotcut-build:qt5.15.1-ubuntu18.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          apt-get update -qq && apt-get install -yqq s3cmd
          cd scripts
          VERSION=$(date +"%%y%%m%%d")
          docker run -v $PWD:/root/shotcut $IMAGE_NAME
          ARCHIVE_NAME=shotcut-linux-x86_64-$VERSION.txz
          mv shotcut.txz $ARCHIVE_NAME
          s3cmd --no-check-certificate --access_key=${{ secrets.AWS_ACCESS_KEY }} \
            --secret_key=${{ secrets.AWS_SECRET_KEY }} --verbose --human-readable-sizes \
            --stop-on-error put $ARCHIVE_NAME s3://builds.us.meltytech/shotcut/
